# Generated by Django 5.0.6 on 2024-06-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
