# Generated by Django 5.0.6 on 2024-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_galleryrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
