# Generated by Django 5.0.6 on 2024-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_subcomment_subcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomment',
            name='subcomment',
            field=models.CharField(max_length=500),
        ),
    ]
