name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set dotenv
      run: |
        touch .env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env

    - name: Run Tests
      run: |
        python manage.py test

    - name: webhook
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: CI 성공이Ye~
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        image: ${{ secrets.SUCCESS_IMAGE }}
        color: 0000CD
        url: "https://github.com/sarisia/actions-status-discord"
        username: Ye~

    - name: webhook
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: CI 실패Ye~
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        image: ${{ secrets.FAILED_IMAGE }}
        color: 00FF00
        url: "https://github.com/sarisia/actions-status-discord"
        username: Ye~


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /app/.cd.sh || true

      - name: webhook
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: CICD 성공이Ye~
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.SUCCESS_IMAGE }}
          color: 0000CD
          url: "https://github.com/sarisia/actions-status-discord"
          username: Ye~

      - name: webhook
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: CD 실패Ye~
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.FAILED_IMAGE }}
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: Ye~